on:
  workflow_call:
    inputs:
      rust-version:
        type: string
        required: false
        default: nightly
        description: rust version to use for checks
      additional-dependencies:
        type: string
        required: false
        default: ''
        description: additional dependencies installed using `apt-get`
      working-directory:
        type: string
        required: false
        default: '.'
        description: working directory

jobs:
  check:
    env:
      SQLX_OFFLINE: true
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ inputs.rust-version }}
          override: true

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install additional dependencies
        if: ${{ inputs.additional-dependencies != ''}}
        run: |
          sudo apt-get -y install ${{ inputs.additional-dependencies }}

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: cargo test
