on:
  workflow_call:
    inputs:
      rust-version:
        type: string
        required: false
        default: nightly
        description: rust version to use for checks

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ inputs.rust-version }}
          override: true

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

      - name: Install cargo check tools
        run: |
          cargo install --locked cargo-outdated || true
          cargo install --locked cargo-audit || true
          cargo install --locked cargo-udeps || true

      - name: Check
        run: |
          cargo outdated --exit-code 1
          cargo audit
          cargo udeps

      - name: Test
        run: cargo test
